In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA  
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import pickle

In [7]:
data = pd.read_csv('../student-mat.csv',sep=';')
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [48]:
data.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [8]:
original_features = data[['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences']]
original_features

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,yes,no,no,4,3,4,1,1,3,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,yes,no,5,3,3,1,1,3,4
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,yes,no,4,3,2,2,3,3,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,yes,3,2,2,1,1,5,2
4,GP,F,16,U,GT3,T,3,3,other,other,...,yes,no,no,4,3,2,1,2,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,yes,no,no,5,5,4,4,5,4,11
391,MS,M,17,U,LE3,T,3,1,services,services,...,yes,yes,no,2,4,5,3,4,2,3
392,MS,M,21,R,GT3,T,1,1,other,other,...,yes,no,no,5,5,3,3,3,3,3
393,MS,M,18,R,LE3,T,3,2,services,other,...,yes,yes,no,4,4,1,3,4,5,0
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,yes,yes,no,3,2,3,3,3,5,5

In [9]:
df31 = original_features.replace({'Mjob': {'at_home': 0, 'teacher': 1, 'services': 2, 'health': 3, 'other': 4}})
df32 = df31.replace({'Fjob':{'at_home': 0, 'teacher': 1, 'services': 2, 'health': 3, 'other': 4}})
df33 = df32.replace({'school':{'GP': 0, 'MS': 1}})
df34 = df33.replace({'sex':{'M': 1, 'F': 0}})
df34 = df34.replace({'address':{'U': 1, 'R': 0}})
df35 = df34.replace({'famsize':{'GT3': 0, 'LE3': 1}})
df36 = df35.replace({'Pstatus':{'A': 1, 'T': 0}})
df37 = df36.replace({'higher':{'yes': 1, 'no': 0}})
df38 = df37.replace({'internet':{'yes': 1, 'no': 0}})
df39 = df38.replace({'romantic':{'yes': 1, 'no': 0}})
df41 = df39.replace({'reason':{'course':0,'home':1,'reputation':2,'other':3}})
df42 = df41.replace({'guardian':{'mother':0,'father':1,'other':2}})
df43 = df42.replace({'schoolsup':{'yes': 1, 'no': 0}})
df44 = df43.replace({'famsup':{'yes': 1, 'no': 0}})
df45 = df44.replace({'paid':{'yes': 1, 'no': 0}})
df46 = df45.replace({'activities':{'yes': 1, 'no': 0}})
df47 = df46.replace({'nursery':{'yes': 1, 'no': 0}})



df47.dtypes

school        int64
sex           int64
age           int64
address       int64
famsize       int64
Pstatus       int64
Medu          int64
Fedu          int64
Mjob          int64
Fjob          int64
reason        int64
guardian      int64
traveltime    int64
studytime     int64
failures      int64
schoolsup     int64
famsup        int64
paid          int64
activities    int64
nursery       int64
higher        int64
internet      int64
romantic      int64
famrel        int64
freetime      int64
goout         int64
Dalc          int64
Walc          int64
health        int64
absences      int64
dtype: object

In [10]:
# y = data[['Target']]
y = data['G3'].values
def encode_data(y):
    encoded_data=[]
    for i in y:
        if i>=10:
            encoded_data.append(1)
        if i <10:
            encoded_data.append(0)
    return encoded_data

y=encode_data(y)

In [123]:
# define standard scaler
scaler = StandardScaler()
  
# transform data
X_std = scaler.fit_transform(df47)
X_std = df47.to_numpy()

# X_std = (df47 -df47.mean(axis=0,numeric_only=True)) / df47.std(axis=0)
print(type(X_std))
X_std

<class 'numpy.ndarray'>

array([[ 0,  0, 18, ...,  1,  3,  6],
       [ 0,  0, 17, ...,  1,  3,  4],
       [ 0,  0, 15, ...,  3,  3, 10],
       ...,
       [ 1,  1, 21, ...,  3,  3,  3],
       [ 1,  1, 18, ...,  4,  5,  0],
       [ 1,  1, 19, ...,  3,  5,  5]], dtype=int64)

In [120]:
nb_var=X_std.shape[1] 
nb_var

30

In [54]:
pca = PCA(n_components=X_std.shape[1])

In [55]:
pca.fit(X_std)

PCA(n_components=30)

In [56]:
components = pca.components_
explained_variances = pca.explained_variance_ratio_

In [58]:
# variances = explained_variances
# for i, col in enumerate(X_std.columns):
#     print(f"{col}: {variances[i]}")

In [11]:
y

[0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0]

In [12]:
# X = X_std[['school','sex','age','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob']].values
X=X_std[:,:10]
X

NameError: name 'X_std' is not defined

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.1, random_state=3)

NameError: name 'X' is not defined

In [126]:
#Implementation de l'algorithme de la regression logistique 
class myLogisticRegression:
    
    def __init__(self, l_rate=0.001, iterations=1000):  #assign values for hyper-parameters
        self.l_rate = l_rate  #learning rate
        self.iterations = iterations  #number of iterations

    def fit(self, x, y):  #Fit the training data using Gradient Descent
        self.losses = []  # An empty list to store the error in each iteration
        self.theta = np.zeros((1 + x.shape[1]))  #intitalization,,,Array of zeros 
        n = x.shape[0]  #number of training examples 768
        
        for i in range(self.iterations):
            #Step1
            y_pred = self.theta[0] + np.dot(x, self.theta[1:])  # hypothesis h(x)
            z = y_pred
            #Step2
            g_z =  1 / (1 + np.e**(-z))  #map predicted values to probabilities between 0 & 1      
            
            #Step3
            cost=0
            for iy in y:
                cost += (-iy * np.log(g_z) - (1 - iy) * np.log(1 - g_z))/ n #cost function
            self.losses.append(cost) #Tracking losses
            
            #Step4
            d_theta1 = (1/n) * np.dot(x.T, (g_z - y)) #Derivatives of theta[1:]
            d_theta0 = (1/n) * np.sum(g_z - y)  #Derivatives of theta[0]
            
            #Step5
            self.theta[1:] = self.theta[1:] - self.l_rate * d_theta1  #upadting values of thetas using Gradient descent
            self.theta[0] = self.theta[0] - self.l_rate * d_theta0  #upadting the value of theta 0 using Gradient descent     
        return self
    
    
    def predict(self, x):  #Predicts the value after the model has been trained.
        y_pred = self.theta[0] + np.dot(x, self.theta[1:]) 
        z = y_pred
        g_z = 1 / (1 + np.e**(-z))
        return [1 if i > 0.5 else 0 for i in g_z] #Threshold

In [3]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, Y_train)

NameError: name 'X_train' is not defined

In [65]:
filename = 'trained_model2.sav'
pickle.dump(model, open(filename, 'wb'))

In [128]:
y_pred = model.predict(X_test)
y_pred,X_test

([1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 array([[ 1,  0, 18,  1,  0,  0,  3,  3,  2,  2],
        [ 0,  0, 16,  1,  0,  0,  4,  4,  2,  2],
        [ 0,  0, 17,  1,  0,  0,  4,  4,  1,  1],
        [ 0,  0, 18,  1,  0,  0,  4,  4,  1,  4],
        [ 1,  0, 19,  0,  0,  0,  2,  3,  2,  4],
        [ 0,  1, 17,  1,  0,  0,  2,  1,  4,  4],
        [ 0,  0, 17,  1,  0,  0,  2,  2,  4,  4],
        [ 0,  1, 18,  1,  1,  0,  2,  2,  4,  4],
        [ 0,  1, 17,  1,  1,  0,  1,  1,  3,  4],
        [ 0,  0, 17,  1,  0,  0,  4,  4,  4,  1],
        [ 0,  1, 16,  1,  0,  0,  3,  1,  4,  4],
        [ 0,  1, 17,  1,  1,  0,  2,  3,  2,  2],
        [ 0,  1, 18,  1,  0,  0,  4,  2,  1,  4],
        [ 0,  0, 17,  1,  0,  0,  4,  3,  3,  4],
        [ 0,  0, 19,  1,  0,  0,  3,  3,  4,  4],
        [ 0,  0, 18,  1,  0,  0,  2,  1,  4,  4],
        [ 0,  1, 16,  0,  0,  1,  4,  4,  4,  1],
        [ 0,  0, 16,  1,  0,  1,  2,  1,  4,  4],
        [ 0,  0, 16,  1,  1,  0,  4,  4,  1,  1],
        [ 0,  0, 15,  1,  0,  0,  4,  4,  1,  2],
        [ 0,  0, 15,  1,  0,  1,  4,  3,  2,  2],
        [ 0,  1, 16,  1,  0,  0,  4,  4,  1,  1],
        [ 0,  0, 16,  1,  0,  0,  4,  4,  3,  4],
        [ 0,  0, 16,  1,  1,  0,  2,  2,  4,  4],
        [ 0,  1, 16,  0,  1,  0,  3,  3,  1,  4],
        [ 0,  0, 16,  1,  0,  0,  2,  3,  4,  4],
        [ 0,  1, 18,  1,  1,  0,  3,  4,  2,  4],
        [ 0,  1, 15,  1,  0,  0,  4,  4,  2,  4],
        [ 0,  0, 19,  1,  0,  0,  3,  3,  4,  2],
        [ 0,  0, 15,  0,  0,  0,  2,  4,  2,  3],
        [ 0,  0, 16,  0,  0,  0,  2,  2,  2,  2],
        [ 0,  0, 17,  0,  0,  0,  2,  2,  4,  4],
        [ 1,  0, 18,  1,  1,  0,  1,  1,  0,  2],
        [ 0,  1, 18,  1,  1,  0,  4,  4,  1,  1],
        [ 0,  1, 15,  1,  0,  0,  2,  3,  4,  4],
        [ 1,  1, 17,  0,  0,  0,  4,  3,  2,  4],
        [ 0,  0, 17,  0,  0,  1,  3,  2,  4,  4],
        [ 0,  0, 17,  1,  0,  0,  2,  3,  0,  4],
        [ 0,  1, 15,  0,  0,  0,  3,  4,  0,  1],
        [ 0,  0, 17,  1,  0,  0,  4,  4,  1,  2]], dtype=int64))

In [129]:
def accuracy(y_pred, y_test):
    s=0
    for i in range(len(y_pred)):
        if y_pred[i]==y_test[i]:
            s+= 1
    return s/len(y_test)

In [130]:
acc = accuracy(y_pred,Y_test)
acc*100

67.5

In [131]:
def ConvertSchool(l):
    if l[0]=="GP":
        return 0
    if l[0]=="MS":
        return 1

def ConvertSex(l):
    if l[1]=="M":
        return 1
    if l[1]=="F":
        return 0

def ConvertAddress(l):
    if l[3]=="U":
        return 1
    if l[3]=="R":
        return 0

def ConvertFamsize(l):
    if l[4]=="LE3":
        return 1
    if l[4]=="GT3":
        return 0

def ConvertPstatus(l):
    if l[5]=="T":
        return 0
    if l[5]=="A":
        return 1

def ConvertMedu(l):
    if l[6]==0:
        return 0
    if l[6]==1:
        return 1
    if l[6]==2:
        return 2
    if l[6]==3:
        return 3
    if l[6]==4:
        return 4

def ConvertFedu(l):
    if l[7]==0:
        return 0
    if l[7]==1:
        return 1
    if l[7]==2:
        return 2
    if l[7]==3:
        return 3
    if l[7]==4:
        return 4


def ConvertMjob(l):
    if l[8]=="teacher":
        return 1
    if l[8]=="health":
        return 3
    if l[8]=="services":
        return 2
    if l[8]=="at_home":
        return 0
    if l[8]=="other":
        return 4

def ConvertFjob(l):
    if l[8] == "teacher":
        return 1
    if l[8] == "health":
        return 3
    if l[8] == "services":
        return 2
    if l[8] == "at_home":
        return 0
    if l[8] == "other":
        return 4


def ConvertData(l):
    data = [ConvertSchool(l),ConvertSex(l),l[2],ConvertAddress(l),ConvertFamsize(l),ConvertPstatus(l),ConvertMedu(l),ConvertFedu(l),ConvertMjob(l),ConvertFjob(l)]
    return data

def ConvertClass(x):
    if x==0 :
        return "Failing"
    if x==1:
        return "Successful"

In [70]:

liste2=['Gabriel Pereira','Female',15,'urban',5,'living together','higher education','secondary education','health : care related','services (e.g. administrative or police)']
len(liste2)

10

In [71]:
liste1=['Gabriel Pereira', 'Female', 15, 'urban', 4, 'living together', 'higher education', '5th to 9th grade', 'health : care related', 'services (e.g. administrative or police)']

xx = ConvertData(liste1)
print(xx)
data_converted =  (xx - np.mean(xx)) / np.std(xx)
final_Data = np.array(data_converted)
final = final_Data.reshape((1, 10))
print(final)

#prediction de la classe des donnees
class_pred = model.predict(final)

print("the class is ",class_pred[0])
print("the result is  : ",ConvertClass(class_pred[0]))

[None, None, 15, None, None, None, None, None, None, None]

TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

In [ ]:
X_test

In [75]:
ouss = [[ 2.7509542 , -0.9469754 ,  1.02175064,  0.53471419, -0.63613432,
        -0.33989115,  0.22894388,  0.43969929, -0.2423958 , -0.77069829]]

In [76]:
class_pred1 = model.predict(ouss)

print("the class is ",class_pred1[0])
print("the result is  : ",ConvertClass(class_pred1[0]))

the class is  1
the result is  :  Successful

In [77]:
X

array([[-0.3630498 , -0.94817639,  1.02304645, ...,  1.36037064,
        -1.61224279, -1.56752925],
       [-0.3630498 , -0.94817639,  0.23837976, ..., -1.39997047,
        -1.61224279,  0.82003137],
       [-0.3630498 , -0.94817639, -1.33095364, ..., -1.39997047,
        -1.61224279,  0.82003137],
       ...,
       [ 2.75444305,  1.05465609,  3.37704655, ..., -1.39997047,
         1.12683636,  0.82003137],
       [ 2.75444305,  1.05465609,  1.02304645, ..., -0.47985677,
        -0.24270322,  0.82003137],
       [ 2.75444305,  1.05465609,  1.80771315, ..., -1.39997047,
         1.12683636, -2.36338279]])

In [132]:
used_data=data[['school','sex','age','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob']]
used_data

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

[395 rows x 10 columns]

In [ ]:
df48=df47[['school','sex','age','address','famsize','Pstatus','Medu','Fedu','Mjob','Fjob']]
df48

In [134]:
print(len(used_data))
# scaler = StandardScaler()

for i in used_data.to_numpy():
#     print(i)
    row = ConvertData(i.tolist())

#     row = np.delete(i, list(range(10, 30)))
    print(np.array(row))
#     rowstd = scaler.fit_transform(np.array(row).reshape(-1, 1) )
    
#     print("std",rowstd.tolist())
    
#     l=[]
#     for j in rowstd:
#         for k in j:
#             l.append(k)
#     rowstd=l[::]
#     rowstd = (row - np.mean(row)) / np.std(row)
    print("std",[row])

#     print(rowstd.tolist())
#     print([rowstd.reshape(1, -1)])
    class_pred = model.predict([row])
    #     s=l.predict([row.tolist()])
    if class_pred==[0]:
        print(class_pred)

395
[ 0  0 18  1  0  1  4  4  0  0]
std [[0, 0, 18, 1, 0, 1, 4, 4, 0, 0]]
[ 0  0 17  1  0  0  1  1  0  0]
std [[0, 0, 17, 1, 0, 0, 1, 1, 0, 0]]
[ 0  0 15  1  1  0  1  1  0  0]
std [[0, 0, 15, 1, 1, 0, 1, 1, 0, 0]]
[ 0  0 15  1  0  0  4  2  3  3]
std [[0, 0, 15, 1, 0, 0, 4, 2, 3, 3]]
[ 0  0 16  1  0  0  3  3  4  4]
std [[0, 0, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 16  1  1  0  4  3  2  2]
std [[0, 1, 16, 1, 1, 0, 4, 3, 2, 2]]
[ 0  1 16  1  1  0  2  2  4  4]
std [[0, 1, 16, 1, 1, 0, 2, 2, 4, 4]]
[ 0  0 17  1  0  1  4  4  4  4]
std [[0, 0, 17, 1, 0, 1, 4, 4, 4, 4]]
[ 0  1 15  1  1  1  3  2  2  2]
std [[0, 1, 15, 1, 1, 1, 3, 2, 2, 2]]
[ 0  1 15  1  0  0  3  4  4  4]
std [[0, 1, 15, 1, 0, 0, 3, 4, 4, 4]]
[ 0  0 15  1  0  0  4  4  1  1]
std [[0, 0, 15, 1, 0, 0, 4, 4, 1, 1]]
[ 0  0 15  1  0  0  2  1  2  2]
std [[0, 0, 15, 1, 0, 0, 2, 1, 2, 2]]
[ 0  1 15  1  1  0  4  4  3  3]
std [[0, 1, 15, 1, 1, 0, 4, 4, 3, 3]]
[ 0  1 15  1  0  0  4  3  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 15  1  0  1  2  2  4  4]
std [[0, 1, 15, 1, 0, 1, 2, 2, 4, 4]]
[ 0  0 16  1  0  0  4  4  3  3]
std [[0, 0, 16, 1, 0, 0, 4, 4, 3, 3]]
[ 0  0 16  1  0  0  4  4  2  2]
std [[0, 0, 16, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 16  1  0  0  3  3  4  4]
std [[0, 0, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 17  1  0  0  3  2  2  2]
std [[0, 1, 17, 1, 0, 0, 3, 2, 2, 2]]
[ 0  1 16  1  1  0  4  3  3  3]
std [[0, 1, 16, 1, 1, 0, 4, 3, 3, 3]]
[ 0  1 15  1  0  0  4  3  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 15  1  0  0  4  4  3  3]
std [[0, 1, 15, 1, 0, 0, 4, 4, 3, 3]]
[ 0  1 16  1  1  0  4  2  1  1]
std [[0, 1, 16, 1, 1, 0, 4, 2, 1, 1]]
[ 0  1 16  1  1  0  2  2  4  4]
std [[0, 1, 16, 1, 1, 0, 2, 2, 4, 4]]
[ 0  0 15  0  0  0  2  4  2  2]
std [[0, 0, 15, 0, 0, 0, 2, 4, 2, 2]]
[ 0  0 16  1  0  0  2  2  2  2]
std [[0, 0, 16, 1, 0, 0, 2, 2, 2, 2]]
[ 0  1 15  1  0  0  2  2  4  4]
std [[0, 1, 15, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 15  1  0  0  4  2  3  3]
std [[0, 1, 15, 1, 0, 0, 4, 2, 3, 3]]
[ 0  1 16  1  1  1  3  4  2  2]
std [[0, 1, 16, 1, 1, 1, 3, 4, 2, 2]]
[ 0  1 16  1  0  0  4  4  1  1]
std [[0, 1, 16, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 15  1  0  0  4  4  3  3]
std [[0, 1, 15, 1, 0, 0, 4, 4, 3, 3]]
[ 0  1 15  1  0  0  4  4  2  2]
std [[0, 1, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 15  0  0  0  4  3  1  1]
std [[0, 1, 15, 0, 0, 0, 4, 3, 1, 1]]
[ 0  1 15  1  1  0  3  3  4  4]
std [[0, 1, 15, 1, 1, 0, 3, 3, 4, 4]]
[ 0  1 16  1  0  0  3  2  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 2, 4, 4]]
[ 0  0 15  1  0  0  2  3  4  4]
std [[0, 0, 15, 1, 0, 0, 2, 3, 4, 4]]
[ 0  1 15  1  1  0  4  3  1  1]
std [[0, 1, 15, 1, 1, 0, 4, 3, 1, 1]]
[ 0  1 16  0  0  1  4  4  4  4]
std [[0, 1, 16, 0, 0, 1, 4, 4, 4, 4]]
[ 0  0 15  0  0  0  3  4  2  2]
std [[0, 0, 15, 0, 0, 0, 3, 4, 2, 2]]
[ 0  0 15  0  0  0  2  2  0  0]
std [[0, 0, 15, 0, 0, 0, 2, 2, 0, 0]]
[ 0  0 16  1  1  0  2  2  4  4]
std [[0, 0, 16, 1, 1, 0, 2, 2, 4, 4]]
[ 0  1 15  1  1  0  4  4  1  1]
std [[0, 1, 15, 1, 1, 0, 4, 4, 1, 1]]
[ 0  1 15  1  0  0  4  4  2  2]
std [[0, 1, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 15  1  0  0  2  2  2  2]
std [[0, 1, 15, 1, 0, 0, 2, 2, 2, 2]]
[ 0  0 16  1  1  0  2  2  4  4]
std [[0, 0, 16, 1, 1, 0, 2, 2, 4, 4]]
[ 0  0 15  1  1  1  4  3  4  4]
std [[0, 0, 15, 1, 1, 1, 4, 3, 4, 4]]
[ 0  0 16  1  1  1  3  3  4  4]
std [[0, 0, 16, 1, 1, 1, 3, 3, 4, 4]]
[ 0  1 16  1  0  0  4  3  3  3]
std [[0, 1, 16, 1, 0, 0, 4, 3, 3, 3]]
[ 0  1 15  1  0  0  4  2  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 2, 1, 1]]
[ 0  0 15  1  0  0  4  4  2  2]
std [[0, 0, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 16  1  1  0  2  2  2  2]
std [[0, 0, 16, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 15  1  1  0  4  2  3  3]
std [[0, 0, 15, 1, 1, 0, 4, 2, 3, 3]]
[ 0  1 15  1  1  1  4  2  3  3]
std [[0, 1, 15, 1, 1, 1, 4, 2, 3, 3]]
[ 0  0 15  1  0  0  4  4  2  2]
std [[0, 0, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 15  1  1  1  3  3  4  4]
std [[0, 0, 15, 1, 1, 1, 3, 3, 4, 4]]
[ 0  0 16  1  0  1  2  1  4  4]
std [[0, 0, 16, 1, 0, 1, 2, 1, 4, 4]]
[ 0  0 15  1  0  1  4  3  2  2]
std [[0, 0, 15, 1, 0, 1, 4, 3, 2, 2]]
[ 0  1 15  1  0  0  4  4  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 15  1  1  0  1  2  4  4]
std [[0, 1, 15, 1, 1, 0, 1, 2, 4, 4]]
[ 0  0 16  1  0  0  4  2  2  2]
std [[0, 0, 16, 1, 0, 0, 4, 2, 2, 2]]
[ 0  0 16  0  0  0  4  4  3  3]
std [[0, 0, 16, 0, 0, 0, 4, 4, 3, 3]]
[ 0  0 16  1  0  0  1  1  2  2]
std [[0, 0, 16, 1, 0, 0, 1, 1, 2, 2]]
[ 0  0 16  1  1  0  1  2  4  4]
std [[0, 0, 16, 1, 1, 0, 1, 2, 4, 4]]
[ 0  0 16  1  0  0  4  3  1  1]
std [[0, 0, 16, 1, 0, 0, 4, 3, 1, 1]]
[ 0  0 15  1  1  0  4  3  2  2]
std [[0, 0, 15, 1, 1, 0, 4, 3, 2, 2]]
[ 0  0 16  1  1  0  4  3  1  1]
std [[0, 0, 16, 1, 1, 0, 4, 3, 1, 1]]
[ 0  1 15  1  0  1  4  4  4  4]
std [[0, 1, 15, 1, 0, 1, 4, 4, 4, 4]]
[ 0  0 16  1  0  0  3  1  2  2]
std [[0, 0, 16, 1, 0, 0, 3, 1, 2, 2]]
[ 0  0 15  0  1  0  2  2  3  3]
std [[0, 0, 15, 0, 1, 0, 2, 2, 3, 3]]
[ 0  0 15  0  1  0  3  1  4  4]
std [[0, 0, 15, 0, 1, 0, 3, 1, 4, 4]]
[ 0  1 16  1  0  0  3  1  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 1, 4, 4]]
[ 0  1 15  1  0  0  4  2  4  4]
std [[0, 1, 15, 1, 0, 0, 4, 2, 4, 4]]
[ 0  0 15  0  0  0  1  1  4  4]
std [[0, 0, 15, 0, 0, 0, 1, 1, 4, 4]]
[ 0  1 16  1  0  0  3  1  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 1, 4, 4]]
[ 0  0 16  1  0  0  3  3  4  4]
std [[0, 0, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 15  1  0  0  4  3  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 15  1  0  0  4  0  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 0, 1, 1]]
[ 0  0 16  1  0  0  2  2  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 17  1  0  0  2  1  4  4]
std [[0, 1, 17, 1, 0, 0, 2, 1, 4, 4]]
[ 0  0 16  1  0  0  3  4  0  0]
std [[0, 0, 16, 1, 0, 0, 3, 4, 0, 0]]
[ 0  1 15  1  0  0  2  3  4  4]
std [[0, 1, 15, 1, 0, 0, 2, 3, 4, 4]]
[ 0  1 15  1  0  0  2  3  4  4]
std [[0, 1, 15, 1, 0, 0, 2, 3, 4, 4]]
[ 0  0 15  1  1  0  3  2  2  2]
std [[0, 0, 15, 1, 1, 0, 3, 2, 2, 2]]
[ 0  1 15  1  1  0  2  2  2  2]
std [[0, 1, 15, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 15  1  0  0  1  1  4  4]
std [[0, 0, 15, 1, 0, 0, 1, 1, 4, 4]]
[ 0  0 15  1  0  0  4  4  2  2]
std [[0, 0, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 16  1  1  0  2  2  0  0]
std [[0, 0, 16, 1, 1, 0, 2, 2, 0, 0]]
[ 0  0 15  1  0  0  4  2  4  4]
std [[0, 0, 15, 1, 0, 0, 4, 2, 4, 4]]
[ 0  1 16  1  0  0  2  2  2  2]
std [[0, 1, 16, 1, 0, 0, 2, 2, 2, 2]]
[ 0  1 16  1  1  1  4  4  1  1]
std [[0, 1, 16, 1, 1, 1, 4, 4, 1, 1]]
[ 0  0 16  1  0  0  3  3  4  4]
std [[0, 0, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  0 15  1  0  0  4  3  2  2]
std [[0, 0, 15, 1, 0, 0, 4, 3, 2, 2]]
[ 0  0 16  1  1  0  3  1  4  4]
std [[0, 0, 16, 1, 1, 0, 3, 1, 4, 4]]
[ 0  0 16  1  0  0  4  2  1  1]
std [[0, 0, 16, 1, 0, 0, 4, 2, 1, 1]]
[ 0  1 15  1  1  0  2  2  2  2]
std [[0, 1, 15, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 15  0  0  0  1  1  0  0]
std [[0, 0, 15, 0, 0, 0, 1, 1, 0, 0]]
[ 0  1 16  0  0  0  4  3  2  2]
std [[0, 1, 16, 0, 0, 0, 4, 3, 2, 2]]
[ 0  0 16  1  0  0  2  1  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 1, 4, 4]]
[ 0  0 16  1  0  0  4  4  4  4]
std [[0, 0, 16, 1, 0, 0, 4, 4, 4, 4]]
[ 0  0 16  1  0  0  4  3  4  4]
std [[0, 0, 16, 1, 0, 0, 4, 3, 4, 4]]
[ 0  1 16  1  0  0  4  4  2  2]
std [[0, 1, 16, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 16  1  0  0  4  4  2  2]
std [[0, 1, 16, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 15  1  0  0  4  4  2  2]
std [[0, 1, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 15  1  0  0  3  2  2  2]
std [[0, 0, 15, 1, 0, 0, 3, 2, 2, 2]]
[ 0  1 15  1  0  1  3  4  2  2]
std [[0, 1, 15, 1, 0, 1, 3, 4, 2, 2]]
[ 0  0 15  1  0  1  3  3  4  4]
std [[0, 0, 15, 1, 0, 1, 3, 3, 4, 4]]
[ 0  0 15  1  0  0  2  2  4  4]
std [[0, 0, 15, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 16  1  0  0  3  3  2  2]
std [[0, 1, 16, 1, 0, 0, 3, 3, 2, 2]]
[ 0  1 15  0  0  0  4  4  4  4]
std [[0, 1, 15, 0, 0, 0, 4, 4, 4, 4]]
[ 0  0 16  1  1  0  4  4  3  3]
std [[0, 0, 16, 1, 1, 0, 4, 4, 3, 3]]
[ 0  1 15  1  1  1  4  4  1  1]
std [[0, 1, 15, 1, 1, 1, 4, 4, 1, 1]]
[ 0  0 16  0  0  0  3  3  2  2]
std [[0, 0, 16, 0, 0, 0, 3, 3, 2, 2]]
[ 0  0 16  1  0  0  2  2  0  0]
std [[0, 0, 16, 1, 0, 0, 2, 2, 0, 0]]
[ 0  1 15  1  1  0  4  2  1  1]
std [[0, 1, 15, 1, 1, 0, 4, 2, 1, 1]]
[ 0  1 15  0  0  0  2  1  3  3]
std [[0, 1, 15, 0, 0, 0, 2, 1, 3, 3]]
[ 0  1 16  1  0  0  4  4  1  1]
std [[0, 1, 16, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 15  1  0  0  4  4  4  4]
std [[0, 1, 15, 1, 0, 0, 4, 4, 4, 4]]
[ 0  1 16  1  0  0  3  3  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 17  0  0  0  1  3  4  4]
std [[0, 1, 17, 0, 0, 0, 1, 3, 4, 4]]
[ 0  1 15  1  0  0  3  4  4  4]
std [[0, 1, 15, 1, 0, 0, 3, 4, 4, 4]]
[ 0  0 15  1  0  0  1  2  0  0]
std [[0, 0, 15, 1, 0, 0, 1, 2, 0, 0]]
[ 0  1 15  1  0  0  2  2  2  2]
std [[0, 1, 15, 1, 0, 0, 2, 2, 2, 2]]
[ 0  0 16  1  1  0  2  4  4  4]
std [[0, 0, 16, 1, 1, 0, 2, 4, 4, 4]]
[ 0  1 16  1  0  0  4  4  3  3]
std [[0, 1, 16, 1, 0, 0, 4, 4, 3, 3]]
[ 0  0 16  1  0  0  2  2  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 15  1  0  0  3  4  2  2]
std [[0, 1, 15, 1, 0, 0, 3, 4, 2, 2]]
[ 0  0 15  1  1  1  3  4  4  4]
std [[0, 0, 15, 1, 1, 1, 3, 4, 4, 4]]
[ 0  0 19  1  0  0  0  1  0  0]
std [[0, 0, 19, 1, 0, 0, 0, 1, 0, 0]]
[ 0  1 18  0  0  0  2  2  2  2]
std [[0, 1, 18, 0, 0, 0, 2, 2, 2, 2]]
[ 0  1 16  0  0  0  4  4  1  1]
std [[0, 1, 16, 0, 0, 0, 4, 4, 1, 1]]
[ 0  0 15  0  0  0  3  4  2  2]
std [[0, 0, 15, 0, 0, 0, 3, 4, 2, 2]]
[ 0  0 15  1  0  0  1  1  0  0]
std [[0, 0, 15, 1, 0, 0, 1, 1, 0, 0]]
[ 0  0 17  1  1  0  2  2  4  4]
std [[0, 0, 17, 1, 1, 0, 2, 2, 4, 4]]
[ 0  0 16  1  0  1  3  4  2  2]
std [[0, 0, 16, 1, 0, 1, 3, 4, 2, 2]]
[ 0  1 15  0  0  0  3  4  0  0]
std [[0, 1, 15, 0, 0, 0, 3, 4, 0, 0]]
[ 0  0 15  1  0  0  4  4  2  2]
std [[0, 0, 15, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 17  0  0  0  3  4  0  0]
std [[0, 1, 17, 0, 0, 0, 3, 4, 0, 0]]
[ 0  0 16  1  0  1  3  3  4  4]
std [[0, 0, 16, 1, 0, 1, 3, 3, 4, 4]]
[ 0  1 16  1  1  0  1  1  2  2]
std [[0, 1, 16, 1, 1, 0, 1, 1, 2, 2]]
[ 0  0 15  1  0  0  4  4  1  1]
std [[0, 0, 15, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 15  1  0  0  4  3  1  1]
std [[0, 1, 15, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 16  1  1  0  2  2  2  2]
std [[0, 1, 16, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 15  1  0  0  4  4  1  1]
std [[0, 0, 15, 1, 0, 0, 4, 4, 1, 1]]
[ 0  0 16  1  1  0  1  1  0  0]
std [[0, 0, 16, 1, 1, 0, 1, 1, 0, 0]]
[ 0  1 17  1  0  0  2  1  4  4]
std [[0, 1, 17, 1, 0, 0, 2, 1, 4, 4]]
[ 0  0 15  1  0  0  1  1  4  4]
std [[0, 0, 15, 1, 0, 0, 1, 1, 4, 4]]
[ 0  0 15  1  0  0  3  2  3  3]
std [[0, 0, 15, 1, 0, 0, 3, 2, 3, 3]]
[ 0  0 15  1  0  0  1  2  0  0]
std [[0, 0, 15, 1, 0, 0, 1, 2, 0, 0]]
[ 0  1 16  1  0  0  4  4  1  1]
std [[0, 1, 16, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 15  1  1  1  2  1  2  2]
std [[0, 1, 15, 1, 1, 1, 2, 1, 2, 2]]
[ 0  1 18  1  1  0  1  1  4  4]
std [[0, 1, 18, 1, 1, 0, 1, 1, 4, 4]]
[ 0  1 16  1  1  0  2  1  0  0]
std [[0, 1, 16, 1, 1, 0, 2, 1, 0, 0]]
[ 0  0 15  0  0  0  3  3  2  2]
std [[0, 0, 15, 0, 0, 0, 3, 3, 2, 2]]
[ 0  1 19  1  0  0  3  2  2  2]
std [[0, 1, 19, 1, 0, 0, 3, 2, 2, 2]]
[ 0  0 17  1  0  0  4  4  4  4]
std [[0, 0, 17, 1, 0, 0, 4, 4, 4, 4]]
[ 0  1 15  0  0  0  2  3  0  0]
std [[0, 1, 15, 0, 0, 0, 2, 3, 0, 0]]
[ 0  1 17  0  1  0  1  2  4  4]
std [[0, 1, 17, 0, 1, 0, 1, 2, 4, 4]]
[ 0  0 18  0  0  0  1  1  0  0]
std [[0, 0, 18, 0, 0, 0, 1, 1, 0, 0]]
[ 0  1 16  0  0  0  2  2  0  0]
std [[0, 1, 16, 0, 0, 0, 2, 2, 0, 0]]
[ 0  1 16  1  0  0  3  3  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 17  0  1  0  2  1  0  0]
std [[0, 1, 17, 0, 1, 0, 2, 1, 0, 0]]
[ 0  1 15  0  0  0  3  2  4  4]
std [[0, 1, 15, 0, 0, 0, 3, 2, 4, 4]]
[ 0  1 16  1  1  0  1  2  4  4]
std [[0, 1, 16, 1, 1, 0, 1, 2, 4, 4]]
[ 0  1 17  1  0  0  1  3  0  0]
std [[0, 1, 17, 1, 0, 0, 1, 3, 0, 0]]
[ 0  1 17  0  1  0  1  1  4  4]
std [[0, 1, 17, 0, 1, 0, 1, 1, 4, 4]]
[ 0  1 16  1  0  0  3  2  2  2]
std [[0, 1, 16, 1, 0, 0, 3, 2, 2, 2]]
[ 0  1 16  1  0  0  2  2  4  4]
std [[0, 1, 16, 1, 0, 0, 2, 2, 4, 4]]
[ 0  0 16  1  0  0  4  2  3  3]
std [[0, 0, 16, 1, 0, 0, 4, 2, 3, 3]]
[ 0  0 16  1  0  0  2  2  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 2, 4, 4]]
[ 0  0 16  1  0  0  4  4  3  3]
std [[0, 0, 16, 1, 0, 0, 4, 4, 3, 3]]
[ 0  1 16  1  0  0  3  4  4  4]
std [[0, 1, 16, 1, 0, 0, 3, 4, 4, 4]]
[ 0  1 16  1  0  0  1  0  4  4]
std [[0, 1, 16, 1, 0, 0, 1, 0, 4, 4]]
[ 0  1 17  1  1  0  4  4  1  1]
std [[0, 1, 17, 1, 1, 0, 4, 4, 1, 1]]
[ 0  0 16  1  0  0  1  3  0  0]
std [[0, 0, 16, 1, 0, 0, 1, 3, 0, 0]]
[ 0  0 16  1  1  0  3  3  4  4]
std [[0, 0, 16, 1, 1, 0, 3, 3, 4, 4]]
[ 0  1 17  1  1  0  4  3  1  1]
std [[0, 1, 17, 1, 1, 0, 4, 3, 1, 1]]
[ 0  0 16  1  0  0  2  2  2  2]
std [[0, 0, 16, 1, 0, 0, 2, 2, 2, 2]]
[ 0  1 17  1  0  0  3  3  4  4]
std [[0, 1, 17, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 16  0  0  0  4  2  1  1]
std [[0, 1, 16, 0, 0, 0, 4, 2, 1, 1]]
[ 0  1 17  1  0  0  4  3  4  4]
std [[0, 1, 17, 1, 0, 0, 4, 3, 4, 4]]
[ 0  1 16  1  0  0  4  3  1  1]
std [[0, 1, 16, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 16  1  0  0  3  3  2  2]
std [[0, 1, 16, 1, 0, 0, 3, 3, 2, 2]]
[ 0  0 17  1  0  0  2  4  2  2]
std [[0, 0, 17, 1, 0, 0, 2, 4, 2, 2]]
[ 0  0 17  1  1  0  3  3  4  4]
std [[0, 0, 17, 1, 1, 0, 3, 3, 4, 4]]
[ 0  0 16  1  0  0  3  2  4  4]
std [[0, 0, 16, 1, 0, 0, 3, 2, 4, 4]]
[ 0  1 17  1  0  0  3  3  2  2]
std [[0, 1, 17, 1, 0, 0, 3, 3, 2, 2]]
[ 0  1 16  1  0  0  1  2  2  2]
std [[0, 1, 16, 1, 0, 0, 1, 2, 2, 2]]
[ 0  1 16  1  1  0  2  1  4  4]
std [[0, 1, 16, 1, 1, 0, 2, 1, 4, 4]]
[ 0  0 17  1  0  1  3  3  3  3]
std [[0, 0, 17, 1, 0, 1, 3, 3, 3, 3]]
[ 0  1 17  0  0  0  1  2  0  0]
std [[0, 1, 17, 0, 0, 0, 1, 2, 0, 0]]
[ 0  0 16  1  0  0  2  3  2  2]
std [[0, 0, 16, 1, 0, 0, 2, 3, 2, 2]]
[ 0  0 17  1  0  0  1  1  0  0]
std [[0, 0, 17, 1, 0, 0, 1, 1, 0, 0]]
[ 0  1 17  1  0  0  1  2  0  0]
std [[0, 1, 17, 1, 0, 0, 1, 2, 0, 0]]
[ 0  1 16  0  0  0  3  3  2  2]
std [[0, 1, 16, 0, 0, 0, 3, 3, 2, 2]]
[ 0  1 16  1  0  0  2  3  4  4]
std [[0, 1, 16, 1, 0, 0, 2, 3, 4, 4]]
[ 0  0 17  1  1  0  2  4  2  2]
std [[0, 0, 17, 1, 1, 0, 2, 4, 2, 2]]
[ 0  1 17  1  0  0  4  4  2  2]
std [[0, 1, 17, 1, 0, 0, 4, 4, 2, 2]]
[ 0  1 16  0  1  0  3  3  1  1]
std [[0, 1, 16, 0, 1, 0, 3, 3, 1, 1]]
[ 0  0 17  1  0  0  4  4  2  2]
std [[0, 0, 17, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 16  1  1  0  4  4  1  1]
std [[0, 0, 16, 1, 1, 0, 4, 4, 1, 1]]
[ 0  0 16  1  0  0  4  3  3  3]
std [[0, 0, 16, 1, 0, 0, 4, 3, 3, 3]]
[ 0  0 16  1  0  0  2  3  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 3, 4, 4]]
[ 0  0 17  1  0  0  1  1  4  4]
std [[0, 0, 17, 1, 0, 0, 1, 1, 4, 4]]
[ 0  0 17  0  0  0  2  2  4  4]
std [[0, 0, 17, 0, 0, 0, 2, 2, 4, 4]]
[ 0  0 16  0  0  0  2  2  2  2]
std [[0, 0, 16, 0, 0, 0, 2, 2, 2, 2]]
[ 0  0 17  1  0  0  3  4  0  0]
std [[0, 0, 17, 1, 0, 0, 3, 4, 0, 0]]
[ 0  0 16  1  0  1  3  1  2  2]
std [[0, 0, 16, 1, 0, 1, 3, 1, 2, 2]]
[ 0  0 16  1  0  0  4  3  1  1]
std [[0, 0, 16, 1, 0, 0, 4, 3, 1, 1]]
[ 0  0 16  1  0  0  1  1  0  0]
std [[0, 0, 16, 1, 0, 0, 1, 1, 0, 0]]
[ 0  0 17  0  0  0  4  3  1  1]
std [[0, 0, 17, 0, 0, 0, 4, 3, 1, 1]]
[ 0  0 19  1  0  0  3  3  4  4]
std [[0, 0, 19, 1, 0, 0, 3, 3, 4, 4]]
[ 0  1 17  1  1  0  4  4  2  2]
std [[0, 1, 17, 1, 1, 0, 4, 4, 2, 2]]
[ 0  0 16  1  0  1  2  2  4  4]
std [[0, 0, 16, 1, 0, 1, 2, 2, 4, 4]]
[ 0  1 18  1  0  0  2  2  2  2]
std [[0, 1, 18, 1, 0, 0, 2, 2, 2, 2]]
[ 0  0 17  0  1  0  4  4  2  2]
std [[0, 0, 17, 0, 1, 0, 4, 4, 2, 2]]
[ 0  0 17  1  1  0  3  2  4  4]
std [[0, 0, 17, 1, 1, 0, 3, 2, 4, 4]]
[ 0  0 17  1  0  0  4  3  4  4]
std [[0, 0, 17, 1, 0, 0, 4, 3, 4, 4]]
[ 0  1 18  1  1  0  3  3  2  2]
std [[0, 1, 18, 1, 1, 0, 3, 3, 2, 2]]
[ 0  0 17  1  0  0  2  3  0  0]
std [[0, 0, 17, 1, 0, 0, 2, 3, 0, 0]]
[ 0  0 17  1  0  0  2  2  0  0]
std [[0, 0, 17, 1, 0, 0, 2, 2, 0, 0]]
[ 0  0 17  0  0  0  2  1  0  0]
std [[0, 0, 17, 0, 0, 0, 2, 1, 0, 0]]
[ 0  0 17  1  0  0  1  1  0  0]
std [[0, 0, 17, 1, 0, 0, 1, 1, 0, 0]]
[ 0  0 16  1  0  0  2  3  2  2]
std [[0, 0, 16, 1, 0, 0, 2, 3, 2, 2]]
[ 0  1 18  1  0  0  2  2  4  4]
std [[0, 1, 18, 1, 0, 0, 2, 2, 4, 4]]
[ 0  0 16  1  0  0  4  4  1  1]
std [[0, 0, 16, 1, 0, 0, 4, 4, 1, 1]]
[ 0  0 18  0  0  0  3  1  4  4]
std [[0, 0, 18, 0, 0, 0, 3, 1, 4, 4]]
[ 0  0 17  1  0  0  3  2  4  4]
std [[0, 0, 17, 1, 0, 0, 3, 2, 4, 4]]
[ 0  1 17  1  1  0  2  3  2  2]
std [[0, 1, 17, 1, 1, 0, 2, 3, 2, 2]]
[ 0  1 18  1  1  0  2  1  0  0]
std [[0, 1, 18, 1, 1, 0, 2, 1, 0, 0]]
[ 0  0 17  1  0  1  2  1  4  4]
std [[0, 0, 17, 1, 0, 1, 2, 1, 4, 4]]
[ 0  0 17  1  1  0  4  3  3  3]
std [[0, 0, 17, 1, 1, 0, 4, 3, 3, 3]]
[ 0  1 17  0  0  0  2  2  4  4]
std [[0, 1, 17, 0, 0, 0, 2, 2, 4, 4]]
[ 0  1 17  1  0  0  4  4  1  1]
std [[0, 1, 17, 1, 0, 0, 4, 4, 1, 1]]
[ 0  1 16  1  0  0  4  4  3  3]
std [[0, 1, 16, 1, 0, 0, 4, 4, 3, 3]]
[ 0  1 16  1  1  0  1  1  4  4]
std [[0, 1, 16, 1, 1, 0, 1, 1, 4, 4]]
[ 0  1 16  1  0  0  3  2  0  0]
std [[0, 1, 16, 1, 0, 0, 3, 2, 0, 0]]
[ 0  1 17  1  1  0  2  2  4  4]
std [[0, 1, 17, 1, 1, 0, 2, 2, 4, 4]]
[ 0  0 16  1  0  0  2  1  4  4]
std [[0, 0, 16, 1, 0, 0, 2, 1, 4, 4]]
[ 0  0 17  0  0  0  2  1  0  0]
std [[0, 0, 17, 0, 0, 0, 2, 1, 0, 0]]
[ 0  1 18  1  0  0  2  2  4  4]
std [[0, 1, 18, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 17  1  1  0  4  3  3  3]
std [[0, 1, 17, 1, 1, 0, 4, 3, 3, 3]]
[ 0  1 17  0  1  1  4  4  1  1]
std [[0, 1, 17, 0, 1, 1, 4, 4, 1, 1]]
[ 0  1 16  1  1  0  4  3  1  1]
std [[0, 1, 16, 1, 1, 0, 4, 3, 1, 1]]
[ 0  1 16  1  0  0  4  4  2  2]
std [[0, 1, 16, 1, 0, 0, 4, 4, 2, 2]]
[ 0  0 18  1  0  0  2  1  4  4]
std [[0, 0, 18, 1, 0, 0, 2, 1, 4, 4]]
[ 0  1 16  1  0  0  2  1  4  4]
std [[0, 1, 16, 1, 0, 0, 2, 1, 4, 4]]
[ 0  1 17  1  0  0  2  3  4  4]
std [[0, 1, 17, 1, 0, 0, 2, 3, 4, 4]]
[ 0  1 22  1  0  0  3  1  2  2]
std [[0, 1, 22, 1, 0, 0, 3, 1, 2, 2]]
[ 0  1 18  0  1  0  3  3  4  4]
std [[0, 1, 18, 0, 1, 0, 3, 3, 4, 4]]
[ 0  1 16  1  0  0  0  2  4  4]
std [[0, 1, 16, 1, 0, 0, 0, 2, 4, 4]]
[ 0  1 18  1  0  0  3  2  2  2]
std [[0, 1, 18, 1, 0, 0, 3, 2, 2, 2]]
[ 0  1 16  1  0  0  3  3  0  0]
std [[0, 1, 16, 1, 0, 0, 3, 3, 0, 0]]
[ 0  1 18  1  0  0  2  1  2  2]
std [[0, 1, 18, 1, 0, 0, 2, 1, 2, 2]]
[ 0  1 16  0  0  0  2  1  4  4]
std [[0, 1, 16, 0, 0, 0, 2, 1, 4, 4]]
[ 0  1 17  0  0  0  2  1  4  4]
std [[0, 1, 17, 0, 0, 0, 2, 1, 4, 4]]
[ 0  1 17  1  1  0  1  1  3  3]
std [[0, 1, 17, 1, 1, 0, 1, 1, 3, 3]]
[ 0  0 17  1  1  0  4  2  1  1]
std [[0, 0, 17, 1, 1, 0, 4, 2, 1, 1]]
[ 0  1 19  1  1  1  4  3  2  2]
std [[0, 1, 19, 1, 1, 1, 4, 3, 2, 2]]
[ 0  1 18  1  0  0  2  1  4  4]
std [[0, 1, 18, 1, 0, 0, 2, 1, 4, 4]]
[ 0  0 17  1  1  0  2  2  2  2]
std [[0, 0, 17, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 18  1  0  0  4  3  2  2]
std [[0, 0, 18, 1, 0, 0, 4, 3, 2, 2]]
[ 0  1 18  1  0  0  4  3  1  1]
std [[0, 1, 18, 1, 0, 0, 4, 3, 1, 1]]
[ 0  1 18  0  0  0  3  2  4  4]
std [[0, 1, 18, 0, 0, 0, 3, 2, 4, 4]]
[ 0  0 17  1  0  0  3  3  4  4]
std [[0, 0, 17, 1, 0, 0, 3, 3, 4, 4]]
[ 0  0 18  1  0  0  2  2  0  0]
std [[0, 0, 18, 1, 0, 0, 2, 2, 0, 0]]
[ 0  1 18  0  1  1  3  4  4  4]
std [[0, 1, 18, 0, 1, 1, 3, 4, 4, 4]]
[ 0  1 17  1  0  0  3  1  2  2]
std [[0, 1, 17, 1, 0, 0, 3, 1, 2, 2]]
[ 0  0 18  0  0  0  4  4  1  1]
std [[0, 0, 18, 0, 0, 0, 4, 4, 1, 1]]
[ 0  1 18  1  0  0  4  2  3  3]
std [[0, 1, 18, 1, 0, 0, 4, 2, 3, 3]]
[ 0  0 18  0  0  0  2  1  4  4]
std [[0, 0, 18, 0, 0, 0, 2, 1, 4, 4]]
[ 0  0 19  1  0  0  3  3  4  4]
std [[0, 0, 19, 1, 0, 0, 3, 3, 4, 4]]
[ 0  0 18  1  0  0  2  3  4  4]
std [[0, 0, 18, 1, 0, 0, 2, 3, 4, 4]]
[ 0  0 18  1  1  0  1  1  4  4]
std [[0, 0, 18, 1, 1, 0, 1, 1, 4, 4]]
[ 0  1 17  0  0  0  1  2  0  0]
std [[0, 1, 17, 0, 0, 0, 1, 2, 0, 0]]
[ 0  0 17  1  0  0  2  4  0  0]
std [[0, 0, 17, 1, 0, 0, 2, 4, 0, 0]]
[ 0  0 17  1  1  0  2  2  2  2]
std [[0, 0, 17, 1, 1, 0, 2, 2, 2, 2]]
[ 0  0 18  0  0  1  3  2  4  4]
std [[0, 0, 18, 0, 0, 1, 3, 2, 4, 4]]
[ 0  1 18  1  0  0  4  4  1  1]
std [[0, 1, 18, 1, 0, 0, 4, 4, 1, 1]]
[ 0  0 18  1  0  0  4  4  3  3]
std [[0, 0, 18, 1, 0, 0, 4, 4, 3, 3]]
[ 0  1 18  1  1  0  4  3  1  1]
std [[0, 1, 18, 1, 1, 0, 4, 3, 1, 1]]
[ 0  1 17  1  1  1  4  1  2  2]
std [[0, 1, 17, 1, 1, 1, 4, 1, 2, 2]]
[ 0  1 17  1  1  1  3  2  1  1]
std [[0, 1, 17, 1, 1, 1, 3, 2, 1, 1]]
[ 0  0 18  0  1  0  1  1  0  0]
std [[0, 0, 18, 0, 1, 0, 1, 1, 0, 0]]
[ 0  0 18  1  0  0  1  1  4  4]
std [[0, 0, 18, 1, 0, 0, 1, 1, 4, 4]]
[ 0  0 17  1  0  0  2  2  4  4]
std [[0, 0, 17, 1, 0, 0, 2, 2, 4, 4]]
[ 0  1 17  1  0  0  1  1  4  4]

In [13]:
import pickle

In [14]:
filename = 'titanic_survivor_v1.sav'
pickle.dump(model, open(filename, 'wb'))